# Site settings
title: L.A.K.O.I
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://github.com/agaios/agaios.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: 
encoding: "utf-8"
markdown: kramdown
email:
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
port:    4001
description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
